[package]
name = "chearmyp_token"
version = "0.6.0-dev"
authors = ["Kenneth Trecy Tobias <33564322+KennethTrecy@users.noreply.github.com>"]
edition = "2021"

[dependencies]
abstract_chearmyp_source = { git = "http://chearmyp.local/abstract_chearmyp_source", tag = "v0.4.0" }
abstract_chearmyp_token = { git = "http://chearmyp.local/abstract_chearmyp_token", tag = "v0.2.1" }

[dev-dependencies.abstract_chearmyp_source]
git = "http://chearmyp.local/abstract_chearmyp_source"
tag = "v0.4.0"
features = ["str_source", "vec_source_collection"]

[dev-dependencies.abstract_chearmyp_token]
git = "http://chearmyp.local/abstract_chearmyp_token"
tag = "v0.2.1"
features = ["assertable_token_kind"]

[features]
default = []
no_std = ["abstract_chearmyp_source/no_std", "abstract_chearmyp_token/no_std"]
assertable_token = ["abstract_chearmyp_token/assertable_token_kind"]
